imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# PHPCR config
doctrine_phpcr:
   session:
       backend: "%phpcr_backend%"
       workspace: "%phpcr_workspace%"
       username: "%phpcr_user%"
       password: "%phpcr_pass%"
   odm:
       auto_mapping: true
       auto_generate_proxy_classes: "%kernel.debug%"

# CMF config
cmf_core:
    persistence:
        phpcr:
            enabled: true

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        persistence:
            phpcr:
                route_basepath: /cms/routes
                use_sonata_admin: false
        controllers_by_class:
            Acme\BasicCmsBundle\Document\Page: Acme\BasicCmsBundle\Controller\DefaultController::pageAction
            Acme\BasicCmsBundle\Document\Post: Acme\BasicCmsBundle\Controller\DefaultController::pageAction

cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true

cmf_block:
    persistence:
        phpcr:
            enabled: true

cmf_menu:
    persistence:
        phpcr:
            use_sonata_admin: auto
            content_basepath: /cms/content
            menu_basepath: /cms/content/menu


# Sonata config
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata_admin_doctrine_phpcr.tree_block:
            settings:
                id: '/cms'
            contexts: [admin]

sonata_admin:
    dashboard:
        blocks:
            - { position: right, type: sonata_admin_doctrine_phpcr.tree_block }
            - { position: left, type: sonata.admin.block.admin_list }
    extensions:
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_menu.admin_extension.menu_options:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuOptionsInterface
        cmf_routing.admin_extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_routing.admin_extension.frontend_link:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersReadInterface
            extends:
                - Symfony\Component\Routing\Route

sonata_doctrine_phpcr_admin:
    document_tree_defaults: [locale]
    document_tree:
        Doctrine\ODM\PHPCR\Document\Generic:
            valid_children:
                - all
        Acme\BasicCmsBundle\Document\Site:
            valid_children:
                - all
        Acme\BasicCmsBundle\Document\Page:
            valid_children:
                - Acme\BasicCmsBundle\Document\Post
        Acme\BasicCmsBundle\Document\Post:
            valid_children: []

# Knp menu
knp_menu:
    twig: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

