Acme\BasicCmsBundle\Document\Page:
    uri_schema: /page/{slug}
    token_providers:
        slug: [content_method, { method: getSlug }]

Acme\BasicCmsBundle\Document\Post:
    uri_schema: /post/{date}/{slug}
    token_providers:
        date: [content_datetime, { method: getDate }]
        slug: [content_method, { method: getSlug }]